name: main

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Test
        run: |
          echo "Тестовая сборка main при обычном коммите выполнена!"

# trigger
