name: main

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Test
        run: |
          echo "Настоящая автоматическая сборка проекта uchanin по ТЕГУ запущена успешно!"

# trigger
